machine:
  services:
    - docker

dependencies:
  post:
    - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/ecs-circle-test:$CIRCLE_SHA1 .

test:
  post:
    - docker run -d -p 80:80 --name ecs-circle-test $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/ecs-circle-test:$CIRCLE_SHA1; sleep 10
    - curl --retry 10 --retry-delay 5 localhost:80/test.html | grep "TestIsOk."

deployment:
  prod:
    branch: master
    commands:
      - ./deploy.sh
